FROM ubuntu:16.04

RUN apt-get update \
  && apt-get install -y python3-pip python3-dev \
  && cd /usr/local/bin \
  && ln -s /usr/bin/python3 python \
  && pip3 install --upgrade pip

RUN pip3 install boto3

# Optionally install the requirements.txt.  Ignore it otherwise
ONBUILD RUN pip install -r requirements.txt || [ ! -f requirements.txt ]
