FROM registry.edmodo.io/python37

# The original docker image has problem, it didn't map the requirements.txt, so the file is not installed by default
ADD requirements.txt ./requirements.txt
RUN pip install -r requirements.txt

##### Hack Begin
# Hacking the Boto here
# Event the name is python37, by default, the 16.04 apt installs python3.5

# Option1 download in Docker
# RUN apt-get update && apt-get install -y curl
# ARG GITHUB_ACCESS_TOKEN
# RUN curl -H "Authorization: token ${GITHUB_ACCESS_TOKEN}" \
#          -H 'Accept: application/vnd.github.v3.raw' \
#          -o /tmp/endpoints.json \
#          -L https://raw.githubusercontent.com/edmodo/aws-endpoints/master/python-boto/endpoints.json && \
#     cp /tmp/endpoints.json /usr/local/lib/python3.5/dist-packages/boto/endpoints.json && \
#     rm /tmp/endpoints.json

# Option2 download in Makefile, COPY into Docker
COPY endpoints.json.patch /usr/local/lib/python3.5/dist-packages/boto/endpoints.json
##### Hack End

